export default function () {
  return {
    name: "New Creature",
    tags: [],
    size: "medium",
    type: "monstrosity",
    subtype: "",
    cr: 0,
    alignment: "Neutral Evil",
    ac: 9,
    acdesc: "",
    hp: 0,
    hpdesc: "0 (0d8)+0",
    pc: 0,
    hitdice: 1,
    speed: "30 ft",
    str: 8,
    dex: 8,
    con: 8,
    int: 8,
    wis: 8,
    cha: 8,
    stats: [8, 8, 8, 8, 8, 8],
    skills: [],
    saves: "",
    senses: "",
    damageimmunities: "",
    conditionimmunities: "",
    languages: "",
    damageresistances: "",
    locations: "",
    latlong: [],
    description: ""
  };
}
