export default function () {
  return {
    id: Math.random() + Date.now(),
    name: "New Pet",
    species: "",
    size: "small",
    ac: 10,
    hp: 1,
    hpmax: 1,
    speed: "",
    abilityscores: [0, 0, 0, 0, 0, 0],
    showPetDetails: false,
    equipment: [],
    attacks: [],
    features: "",
    containers: [
      { id: 1, name: "Carried/Worn", capacity: 9999, weightCounts: true, weight: 0 }
    ],
    injuries: [],
    skills: [
      { name: "Strength", prof: 0, stat: 0, magic: 0 },
      { name: "Dexterity", prof: 0, stat: 1, magic: 0 },
      { name: "Constitution", prof: 0, stat: 2, magic: 0 },
      { name: "Intelligence", prof: 0, stat: 3, magic: 0 },
      { name: "Wisdom", prof: 0, stat: 4, magic: 0 },
      { name: "Charisma", prof: 0, stat: 5, magic: 0 },
      { name: "Acrobatics", prof: 0, stat: 1, magic: 0 },
      { name: "Animal Handling", prof: 0, stat: 4, magic: 0 },
      { name: "Arcana", prof: 0, stat: 3, magic: 0 },
      { name: "Athletics", prof: 0, stat: 0, magic: 0 },
      { name: "Deception", prof: 0, stat: 5, magic: 0 },
      { name: "History", prof: 0, stat: 3, magic: 0 },
      { name: "Insight", prof: 0, stat: 4, magic: 0 },
      { name: "Intimidation", prof: 0, stat: 5, magic: 0 },
      { name: "Investigation", prof: 0, stat: 3, magic: 0 },
      { name: "Medicine", prof: 0, stat: 4, magic: 0 },
      { name: "Nature", prof: 0, stat: 3, magic: 0 },
      { name: "Perception", prof: 0, stat: 4, magic: 0 },
      { name: "Performance", prof: 0, stat: 5, magic: 0 },
      { name: "Persuasion", prof: 0, stat: 5, magic: 0 },
      { name: "Religion", prof: 0, stat: 3, magic: 0 },
      { name: "Sleight of Hand", prof: 0, stat: 1, magic: 0 },
      { name: "Stealth", prof: 0, stat: 1, magic: 0 },
      { name: "Survival", prof: 0, stat: 4, magic: 0 }
    ],
    saves: [0, 0, 0, 0, 0, 0],
    dr: {
      piercing: 0,
      slashing: 0,
      bludgeoning: 0,
      mpiercing: 0,
      mslashing: 0,
      mbludgeoning: 0,
      acid: 0,
      cold: 0,
      fire: 0,
      force: 0,
      lightning: 0,
      necrotic: 0,
      poison: 0,
      psychic: 0,
      radiant: 0,
      thunder: 0
    },
    proficiencies: ""
  };
}
