export default function () {
  return {
    name: "",
    tags: [],
    size: "",
    type: "",
    subtype: "",
    cr: 0,
    alignment: "",
    ac: { type: "", default: "" },
    acdesc: "",
    hp: 0,
    hpdesc: "",
    speed: "",
    str: 8,
    dex: 8,
    con: 8,
    int: 8,
    wis: 8,
    cha: 8,
    skills: [],
    saves: "",
    senses: "",
    damageimmunities: "",
    conditionimmunities: "",
    languages: "",
    damageresistances: "",
    locations: "",
    latlong: [],
    description: ""
  }
}