export default [
    { minroll: 1, maxroll: 1, eventText: "You gain 5 levels instantly and find 100000 gold." },
    { minroll: 2, maxroll: 2, eventText: "Roll twice more and use both results. This event can stack." },
    { minroll: 3, maxroll: 3, eventText: "Your people, grateful for your kind rule, give you gifts worth d20 * 20 gp" },
    { minroll: 4, maxroll: 4, eventText: "A caravan of people arrive in town looking for opportunities. Gain 6d6 adults and 2d6 children." },
    { minroll: 5, maxroll: 5, eventText: "A small group arrives in town looking for new opportunities. Gain 3d6 adults and 1d6 children." },
    { minroll: 6, maxroll: 6, eventText: "Unbranded cattle have wandered into town and are captured by the townspeople. Add 200 food to your stockpiles." },
    { minroll: 7, maxroll: 10, eventText: "A wealthy family moves into town, building a manor house and a new random business (private enterprises)." },
    { minroll: 11, maxroll: 11, eventText: "5d6 Kobold prospectors show up at your keep shouting about how they have discovered gold or a rare metal! They offer to mine it for you in exchange for the rights to live in town. (Build a Gold Mine)." },
    { minroll: 12, maxroll: 12, eventText: "5d6 Kobold prospectors show up at your keep shouting about how they have discovered iron or coal! They offer to mine it for you in exchange for the rights to live in town. (Build an Iron Mine or Coal Mine)." },
    { minroll: 13, maxroll: 14, eventText: "A wandering prospector arrives and excitedly proclaims that he has found valuable minerals on your land (1d100, 1-5 rare metal, 6-15 gold, 16-50 coal, 51-90 coal, 91-100, something bad)." },
    { minroll: 15, maxroll: 18, eventText: "Your people find rare edible fruits and mushrooms in the forests. Roll 3d20 and gain that many units of food." },
    { minroll: 19, maxroll: 19, eventText: "You find a cache of money in an unexpected place. Roll 2d100 and gain that much gold." },
    { minroll: 20, maxroll: 23, eventText: "8d8 (3d8 children, 5d8 adults) colonists arrive unexpectedly from one of the Alliance nations (roll randomly), hoping for a place to settle. They bring enough materials and money to build 3 houses and a large farm." },
    { minroll: 24, maxroll: 27, eventText: "A family moves into town. (2 adults, 1d6-1 children)" },
    { minroll: 28, maxroll: 31, eventText: "Workers are particularly productive. Increase revenue by 25% today." },
    { minroll: 32, maxroll: 32, eventText: "Your miners stumble on a cache of buried treasure." },
    { minroll: 33, maxroll: 36, eventText: "A merchant arrives in town offering special wares, including a selection of magic items." },
    { minroll: 37, maxroll: 43, eventText: "A middle class family moves to town and builds a house." },
    { minroll: 44, maxroll: 44, eventText: "Your workers discover an old shed in the woods, filled with booze. Gain 100 alcohol." },
    { minroll: 45, maxroll: 46, eventText: "A wandering cleric comes through town and heals 3d4 people before moving on." },
    { minroll: 47, maxroll: 50, eventText: "An invitation from a neighboring Lord arrives to join them for a feast." },
    { minroll: 51, maxroll: 51, eventText: "A wandering druid casts Plant Growth on one of your farms, doubling its yield for the day." },
    { minroll: 52, maxroll: 53, eventText: "Mercenaries arrive in town and offer their services." },
    { minroll: 54, maxroll: 54, eventText: "An Artificer arrives in town offering to sell a device he has invented." },
    { minroll: 55, maxroll: 57, eventText: "A rare animal is spotted in the woods." },
    { minroll: 58, maxroll: 58, eventText: "One of the townspeople is convinced a family member is a doppleganger." },
    { minroll: 59, maxroll: 59, eventText: "A pair of mages arrive in town separately, begin dueling in the town square, the residents are terrified." },
    { minroll: 60, maxroll: 60, eventText: "A mysterious stranger arrives in town selling cursed items to townsfolk." },
    { minroll: 61, maxroll: 61, eventText: "One of the townsfolk finds a treasure map in the attic left behind by his recently deceased grandfather." },
    { minroll: 62, maxroll: 54, eventText: "An adventurer arrives in town with tales of a lost treasure. His companions fell trying to claim it." },
    { minroll: 65, maxroll: 65, eventText: "A dragon lands in the center of town and takes a nap." },
    { minroll: 66, maxroll: 66, eventText: "A wandering duelist comes to town and challenges one of the players to a duel of honor (to the blood, not the death)" },
    { minroll: 67, maxroll: 72, eventText: "1d6 sick people recover naturally." },
    { minroll: 73, maxroll: 73, eventText: "A worker is injured in an accident (1 adult becomes invalid)." },
    { minroll: 74, maxroll: 74, eventText: "If the number of adults is greater than 450 a worker is injured in an accident (1 adult becomes invalid)." },
    { minroll: 75, maxroll: 75, eventText: "If the number of adults is greater than 900 a worker is injured in an accident (1 adult becomes invalid)." },
    { minroll: 76, maxroll: 76, eventText: "A worker has retired." },
    { minroll: 77, maxroll: 77, eventText: "A baby is born in town." },
    { minroll: 78, maxroll: 78, eventText: "If number of adults is greater than 150 A baby is born in town. Otherwise nothing happens." },
    { minroll: 79, maxroll: 79, eventText: "If the number of adults is greater than 300 a worker has retired. Otherwise nothing happens." },
    { minroll: 80, maxroll: 80, eventText: "If number of adults is greater than 300 A baby is born in town. Otherwise nothing happens." },
    { minroll: 81, maxroll: 81, eventText: "If number of adults is greater than 450 A baby is born in town. Otherwise nothing happens." },
    { minroll: 82, maxroll: 82, eventText: "If the number of adults is greater than 600 a worker has retired. Otherwise nothing happens." },
    { minroll: 83, maxroll: 83, eventText: "If number of adults is greater than 600 A baby is born in town. Otherwise nothing happens." },
    { minroll: 84, maxroll: 84, eventText: "If number of adults is greater than 750 A baby is born in town. Otherwise nothing happens." },
    { minroll: 85, maxroll: 85, eventText: "If the number of adults is greater than 900 a worker has retired. Otherwise nothing happens." },
    { minroll: 86, maxroll: 86, eventText: "If number of adults is greater than 900 A baby is born in town. Otherwise nothing happens." },
    { minroll: 87, maxroll: 87, eventText: "If number of adults is greater than 1050 A baby is born in town. Otherwise nothing happens." },
    { minroll: 88, maxroll: 88, eventText: "If the number of adults is greater than 1200 a worker has retired. Otherwise nothing happens." },
    { minroll: 89, maxroll: 89, eventText: "If number of adults is greater than 1200 A baby is born in town. Otherwise nothing happens." },
    { minroll: 90, maxroll: 90, eventText: "A new private business is founded." },
    { minroll: 91, maxroll: 95, eventText: "If number of homeless people is greater than 0, your people build a house (private enterprise), otherwise nothing happens." },
    { minroll: 96, maxroll: 100, eventText: "If number of available staff beds is less than 3, your people build a staff house (private enterprise), otherwise nothing happens." },
    { minroll: 101, maxroll: 105, eventText: "If number of homeless people is greater than 0, your people build a log cabin (private enterprise), otherwise nothing happens." },
    { minroll: 106, maxroll: 110, eventText: "Nothing interesting happens." },
    { minroll: 111, maxroll: 111, eventText: "If number of sick/elderly is greater than 1200, an elderly person dies. Otherwise nothing happens." },
    { minroll: 112, maxroll: 112, eventText: "If the number of children is greater than 1200 a child has reached adulthood (1 child becomes an adult). Otherwise nothing happens." },
    { minroll: 113, maxroll: 113, eventText: "If the number of children is greater than 1050 a child has reached adulthood (1 child becomes an adult). Otherwise nothing happens." },
    { minroll: 114, maxroll: 114, eventText: "If number of sick/elderly is greater than 900, an elderly person dies. Otherwise nothing happens." },
    { minroll: 115, maxroll: 115, eventText: "If the number of children is greater than 900 a child has reached adulthood (1 child becomes an adult). Otherwise nothing happens." },
    { minroll: 116, maxroll: 116, eventText: "If the number of children is greater than 750 a child has reached adulthood (1 child becomes an adult). Otherwise nothing happens." },
    { minroll: 117, maxroll: 117, eventText: "If number of sick/elderly is greater than 600, an elderly person dies. Otherwise nothing happens." },
    { minroll: 118, maxroll: 118, eventText: "If the number of children is greater than 600 a child has reached adulthood (1 child becomes an adult). Otherwise nothing happens." },
    { minroll: 119, maxroll: 119, eventText: "If the number of children is greater than 450 a child has reached adulthood (1 child becomes an adult). Otherwise nothing happens." },
    { minroll: 120, maxroll: 120, eventText: "If number of sick/elderly is greater than 300, an elderly person dies. Otherwise nothing happens." },
    { minroll: 121, maxroll: 121, eventText: "If the number of children is greater than 300 a child has reached adulthood (1 child becomes an adult). Otherwise nothing happens." },
    { minroll: 122, maxroll: 122, eventText: "An elderly person in town dies." },
    { minroll: 123, maxroll: 123, eventText: "A child has reached adulthood (1 child becomes an adult)." },
    { minroll: 124, maxroll: 125, eventText: "A group of adventurers wanders through town." },
    { minroll: 126, maxroll: 126, eventText: "A mercenary arrives in town looking for work (fighter level 2d4+2)" },
    { minroll: 127, maxroll: 127, eventText: "A cleric arrives in town looking for work (cleric level 2d4+2)" },
    { minroll: 128, maxroll: 129, eventText: "Taxes are due! Pay 5 * your gross daily gold revenue." },
    { minroll: 130, maxroll: 130, eventText: "3d4 (1d4 children, 1d4 adults, 1d4 invalids) Refugees arrive at your town begging for a place to live." },
    { minroll: 131, maxroll: 131, eventText: "3d6 (1d6 children, 1d6 adults, 1d6 invalids) Refugees arrive at your town begging for a place to live." },
    { minroll: 132, maxroll: 132, eventText: "3d8 (1d8 children, 1d8 adults, 1d8 invalids) Refugees arrive at your town begging for a place to live." },
    { minroll: 133, maxroll: 133, eventText: "6d4 (2d4 children, 2d4 adults, 2d4 invalids) Refugees arrive at your town begging for a place to live." },
    { minroll: 134, maxroll: 134, eventText: "6d6 (2d6 children, 2d6 adults, 2d6 invalids) Refugees arrive at your town begging for a place to live." },
    { minroll: 135, maxroll: 135, eventText: "6d8 (2d8 children, 2d8 adults, 2d8 invalids) Refugees arrive at your town begging for a place to live." },
    { minroll: 136, maxroll: 138, eventText: "Exceptionally beautiful weather has left the townsfolk in a good mood, reduce the effect of unrest on your next roll by 2." },
    { minroll: 139, maxroll: 140, eventText: "Your construction workers have been unusually productive, any buildings you actively have under construction progress an extra 20 laborer-days towards completion." },
    { minroll: 141, maxroll: 142, eventText: "The local children snuck away to go fishing, and had a bumper catch. Gain 1d10 food." },
    { minroll: 143, maxroll: 144, eventText: "A lost but apparently domesticated animal wanders into town." },
    { minroll: 145, maxroll: 146, eventText: "A traveling bard passes through town." },
    { minroll: 147, maxroll: 149, eventText: "A wandering cleric passes through town and gives a sermon in town." },
    { minroll: 150, maxroll: 150, eventText: "A wandering wizard comes through town looking for work and a place to study (wizard level 2d4+2)." },
    { minroll: 151, maxroll: 151, eventText: "A skilled fighter wanders through town (fighter level 3d4+2)." },
    { minroll: 152, maxroll: 153, eventText: "A creepy looking mage wanders into town. He says he means no harm, but the people find him unsettling." },
    { minroll: 154, maxroll: 156, eventText: "An ill omen appears, unsettling the townsfolk. The effect of unrest on your next roll is increased by 2." },
    { minroll: 157, maxroll: 157, eventText: "A chromatic dragon attacks and demands tribute from the town." },
    { minroll: 158, maxroll: 158, eventText: "A townsperson made a deal with a hag that they regret, they will give anything to have it undone." },
    { minroll: 159, maxroll: 160, eventText: "River pirates attack the town." },
    { minroll: 161, maxroll: 161, eventText: "A necromancer has raided the town graveyard and loosed his creations on the town." },
    { minroll: 162, maxroll: 162, eventText: "A random magical occurance causes an abberation to appear in the middle of town and start causing havoc." },
    { minroll: 163, maxroll: 164, eventText: "A leak springs in the roof of the keep, right above one of your beds. Roll to determine which party member has a bad nights sleep." },
    { minroll: 165, maxroll: 167, eventText: "A sudden illness kills some of your livestock, lose 2d20 food." },
    { minroll: 168, maxroll: 170, eventText: "A large storm causes damage to some buildings. It will cost 2d100 for repairs." },
    { minroll: 171, maxroll: 171, eventText: "A person falls out of the sky, splattering on the ground. No one saw what happened." },
    { minroll: 172, maxroll: 173, eventText: "Apparently its a local holiday, all the shops in town are closed." },
    { minroll: 174, maxroll: 174, eventText: "Some of the children have gone missing. The parents beg you to help them." },
    { minroll: 175, maxroll: 176, eventText: "Your construction workers are delayed by an accident, any buildings you actively have under construction are delayed by a day." },
    { minroll: 177, maxroll: 177, eventText: "Some nearby fey folk are causing trouble for the towns lumberjacks." },
    { minroll: 178, maxroll: 179, eventText: "Slave hunters arrive claiming some of your townsfolk are escaped slaves. They are beligerent and insistent." },
    { minroll: 180, maxroll: 180, eventText: "There is a murder in town! The people beg the players to investigate." },
    { minroll: 181, maxroll: 181, eventText: "A wolf pack has killed some sheep on a farm you own. Lose 100 food, and it has a 25% chance of happening again each day until the wolves are found and dealt with." },
    { minroll: 182, maxroll: 182, eventText: "People die in a tragic accident, 1d6 people die." },
    { minroll: 183, maxroll: 185, eventText: "There is a Monster lurking near town (roll randomly to determine type)." },
    { minroll: 186, maxroll: 186, eventText: "A large group of townspeople have joined a suspicious cult, your steward is concerned." },
    { minroll: 187, maxroll: 187, eventText: "A large group of townspeople have converted to a new religion." },
    { minroll: 188, maxroll: 189, eventText: "Flooding in town causes damage to several buildings." },
    { minroll: 190, maxroll: 190, eventText: "Some of your people are convinced by wandering adventurers to join their quest. 1d4 adults leave town." },
    { minroll: 191, maxroll: 191, eventText: "Plague sweeps into town, sickening 2d6 people per day until it is dealt with." },
    { minroll: 192, maxroll: 193, eventText: "Robbery! Robbers break into the keep in the night and attempt to make off with any stored gold." },
    { minroll: 194, maxroll: 194, eventText: "A chromatic dragon demands tribute or it will burn the town." },
    { minroll: 195, maxroll: 195, eventText: "Graves have been dug up in the night, the Steward suspects a necromancer." },
    { minroll: 196, maxroll: 199, eventText: "People leave your town. 3d6 people (1d6 children and 2d6 adults) leave town to find a new home." },
    { minroll: 200, maxroll: 200, eventText: "Roll twice more and use both results. This event can stack." },
    { minroll: 201, maxroll: 202, eventText: "One of the loyalists in town is attacked by a mob and killed." },
    { minroll: 203, maxroll: 205, eventText: "Revolutionaries attack and attempt to take the town!" },
    { minroll: 206, maxroll: 207, eventText: "Work strike happens. 50% of yesterdays income lost. Will continue until demands are met or otherwise dealt with." },
    { minroll: 208, maxroll: 210, eventText: "Revolt. The people in your village are taking up arms to attack you!" },
    { minroll: 211, maxroll: 213, eventText: "Drug problems are sweeping through town causing working adults to become sick. 1d6 people each day become sick until it is dealt with." },
    { minroll: 214, maxroll: 215, eventText: "Starving people have begun to grow sick, 2d6 adults become invalids" },
    { minroll: 216, maxroll: 218, eventText: "An Assassin strikes in the night attempting to kill one of the players or a member of their staff." },
    { minroll: 219, maxroll: 219, eventText: "A lycanthrope has bitten some people in your town. If not dealt with, it is likely to spread." },
    { minroll: 220, maxroll: 220, eventText: "Arsonists strike in the night burning down a random building. The cost to rebuild depends on the building and the effectiveness of the response." },
    { minroll: 221, maxroll: 222, eventText: "Petty criminals plague the town, robbing houses and picking pockets. Tax revenues are reduced by 25% until they are dealt with, and things in storage may randomly disappear." },
    { minroll: 223, maxroll: 224, eventText: "Starving people have raided your storehouses, stealing all of your stored food." },
    { minroll: 225, maxroll: 500, eventText: "Revolt. The people in your village are taking up arms to attack you!" }
  ];